language: node_js
node_js:
  - '0.10'
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'nver' ]; then cd .. && eval "mv $currentfolder nver" && cd nver; fi
install: npm install
script: grunt test